print("This is my first initial")
print("++++++++++++++++++++++++++++++++++++++++")
print("+ BBBBBBBBBBBBBBBBB                    +")
print("+ BBBBBBBBBBBBBBBBBBB                  +")
print("+ BBBBBB         BBBBBBB               +")
print("+ BBBBBB           BBBBBBB             +")
print("+ BBBBBB            BBBBBBBB           +")
print("+ BBBBBB           BBBBBBBB            +")
print("+ BBBBBB          BBBBBBB              +")
print("+ BBBBBB         BBBBB                 +")
print("+ BBBBBB    BBBBBB                     +")
print("+ BBBBBBBBBBBBBBB                      +")
print("+ BBBBBBBBBBBBBBBBB                    +")
print("+ BBBBBBBBBBBBBBB                      +")
print("+ BBBBBB      BBBBBBBBB                +")
print("+ BBBBBB        BBBBBBBBB              +")
print("+ BBBBBB        BBBBBBBBBB             +")
print("+ BBBBBB        BBBBBBBB               +")
print("+ BBBBBB      BBBBBBBB                 +")
print("+ BBBBBB     BBBBBBBB                  +")
print("+ BBBBBBBBBBBBBBBBB                    +")
print("++++++++++++++++++++++++++++++++++++++++")