from tkinter import*
root = Tk()
root.title("CMPT111 Lab 11")
root.minsize(750,450)
root.config(bg="cyan")

def f1():
    title = Label(text="The tune's title is "+ E1.get(),bg="cyan", fg="SpringGreen4" )
    title.place(x=20,y=290)
    name = Label(text="The performer's name is "+ E2.get(),bg="cyan", fg="SpringGreen4" )
    name.place(x=20,y=320)
    length = Label(text="The tune's length is "+ E3.get(),bg="cyan", fg="SpringGreen4" )
    length.place(x=20,y=350)
    label = Label(text="The label is "+ E4.get(),bg="cyan", fg="SpringGreen4" )
    label.place(x=20,y=380)
    format = Label(text="The format is "+ E5.get(),bg="cyan", fg="SpringGreen4" )
    format.place(x=300,y=290)
    genre = Label(text="The genre is "+ E6.get(),bg="cyan", fg="SpringGreen4" )
    genre.place(x=300,y=320)
    release = Label(text="The year of release is "+ E7.get(),bg="cyan", fg="SpringGreen4" )
    release.place(x=300,y=350)


l1 = Label(text="Enter the tune's title: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l1.place(x=20,y=20)
l2 = Label(text="Enter the performer's name: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l2.place(x=20,y=70)
l3 = Label(text="Enter the tune's length: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l3.place(x=20,y=120)
l4 = Label(text="Enter the label: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l4.place(x=20,y=170)
l5 = Label(text="Enter the format: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l5.place(x=300,y=20)
l6 = Label(text="Enter the genre: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l6.place(x=300,y=70)
l7 = Label(text="Enter the year of release: ", bg="cyan", fg="SpringGreen4", font="Arial 10")
l7.place(x=300,y=120)

E1 = Entry(bg="white")
E1.place(x=20,y=40)
E2 = Entry(bg="white")
E2.place(x=20,y=90)
E3 = Entry(bg="white")
E3.place(x=20,y=140)
E4 = Entry(bg="white")
E4.place(x=20,y=190)
E5 = Entry(bg="white")
E5.place(x=300,y=40)
E6 = Entry(bg="white")
E6.place(x=300,y=90)
E7 = Entry(bg="white")
E7.place(x=300,y=140)

B1 = Button(text="Click here to see the results", bg="AntiqueWhite1", fg="SpringGreen4", activebackground="SpringGreen4", activeforeground="white", font="Arial 10", command=f1)
B1.place(x=20, y=250)


root.mainloop()